version: "3"
networks:
  default:
    external:
      name: bridge
services:
  proxy:
    image: steamcache/sniproxy:latest
    ports:
      - "443"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "${PWD}/sniproxy.conf:/etc/sniproxy.conf"  
