version: "3"
services:
  proxy:
    image: steamcache/sniproxy:latest
    network_mode: "host"
    ports:
      - "443"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "${PWD}/sniproxy.conf:/etc/sniproxy.conf"  
